### ISSUE TITLE
Support for Contigs File as Input for RNA Virus Identification

### ISSUE THREAD

**Issue by linzhl1** [ZiyueYang01/VirID#13]
Hi developer,

Thank you for developing VirID, an excellent RNA virus discovery and characterization tool. I have a question regarding the input files for RNA virus identification.

Does VirID only accept raw reads files as input for identifying RNA viruses? If so, would it be possible to add support for contig files assembled by Megahit as input for RNA virus identification?

This feature would benefit users who have already performed assembly and want to use the contigs directly.

Thank you for considering this request!

**Comment by ZiyueYang01** [comment]
You can run it like this:
```
VirID phylogenetic_analysis -classify_i test/test_contig.fasta \
	-out_dir out_path --threads 90 --keep_dup
```
The phylogenetic_analysis mode use contigs as input.

**Comment by linzhl1** [comment]
Thank you for getting back to me so quickly.
