### ISSUE TITLE
Viral sequence database is not accessible.

### ISSUE THREAD

**Issue by cerebis** [ZiyueYang01/VirID#2]
The link 

https://zenodo.org/records/10435588/files/VirID_rRNA_db.fasta.bz2?download=1&preview=1

is not publicly accessible, Zenodo giving the message:

`You do not have sufficient permissions to view this page.`

**Comment by ZiyueYang01** [comment]
We change the link, you can download the database at: https://drive.google.com/file/d/1PDbuIG1ZcMRWrQ8nhE50p33B2J1IposQ/view?usp=sharing

**Comment by cerebis** [comment]
Great. Thanks.

**Comment by cerebis** [comment]
Btw, for shell-based systems, Google drive can be an awkward service from which to obtain files. I really don't want to DL it to my local machine and then push it back to an HPC over piddly Australian broadband. 

The easiest tool for this task is the Python based [gdown](https://github.com/wkentaro/gdown)

Where, I got your file using the following.

```bash
gdown --fuzzy "https://drive.google.com/file/d/1PDbuIG1ZcMRWrQ8nhE50p33B2J1IposQ/view?usp=sharing"
```

Fuzzy is required, since you've provided a sharing link rather than the direct file ID. The quotes are also needed to prevent the shell parsing the URL.
