### ISSUE TITLE
Clarification of NT documentation.

### ISSUE THREAD

**Issue by cerebis** [ZiyueYang01/VirID#6]
After users have accomplished the tasks documented in the NT markdown, where do the results go?

From other preparation steps, I have guessed `${VirID_DB_PATH}/db/NT`. 

Is this incorrect?

**Comment by ZiyueYang01** [comment]
It's `${VirID_DB_PATH}/NT`，you can check it in `VirID/config/config.py`.

The address and name of the final built library, which can be used for _diamond_, should be: `${VirID_DB_PATH}/NT/nt`
